version: '3'
services:
  csv-voucher-importer-api:
    image: csv-voucher-importer:latest
    depends_on: 
      - db
    ports:
      - "9000:9000" # left part is on the host, right part is on inside the container
      - "9229:9229"
    environment:
      - DB_HOST=172.16.239.10
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=pass
      - PORT=9000
      - HOST=0.0.0.0    
    networks:
      local:
        ipv4_address: 172.16.239.11
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=default
    command: --default-authentication-plugin=mysql_native_password
    networks:
      local:
        aliases:
          - database
        ipv4_address: 172.16.239.10
networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.239.0/24      